
spring.application.name=STB Bank Platform

# Server
server.port=8089
server.address=0.0.0.0
# PostgreSQL (Supabase) — production/persistant
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.cwgfmwbnudxxirrpdpud
spring.datasource.password=Siwar214321*
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de connexions (important avec le pooler Supabase)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Data initialization (à désactiver après le premier lancement si vous avez un data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.tn.stb=DEBUG
logging.level.org.springframework.security=WARN


spring.security.oauth2.client.registration.keycloak.client-id=stb-bank-client
spring.security.oauth2.client.registration.keycloak.client-secret=13bAJwzNyxLIyE2YF1OXAY6drhgAdurfC49zy9AGeXEet1yBXbERXbx8GadkIp5xeEDfEzaphJHGYMeimGRz8R
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://192.168.96.133:8080/realms/stb-bank



opa.url=http://192.168.96.133:8181/v1/data/stb/authz/allow_validation
opa.deletion-url=http://192.168.96.133:8181/v1/data/stb/authz/allow_deletion
